{{- if .Values.frontend.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.frontend.name }}
  namespace: {{ .Values.namespace | quote }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ .Values.frontend.name }}
{{- end }}
---
{{- if .Values.backend.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Values.backend.name }}
  namespace: {{ .Values.namespace | quote }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: {{ .Values.backend.name }}
{{- end }}
